default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: backend_development
  host: localhost
  port: 5432
  username: postgres
  password: 1qaz2wsx

test:
  <<: *default
  database: backend_test
  host: localhost
  port: 5432
  username: postgres
  password: 1qaz2wsx
  pool: 5

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
